title : La villa de Diomède
title_complet : Une exploration virtuelle à Pompéi
title_alt : Pompéi
baseurl: /expo
url_complet: "http://villadiomede.huma-num.fr/expo"
exclude:
  - README.MD
  - potree/pointclouds

producteur: Villa Diomedes Project
producteur_complement: AOROC UMR 8546 Ecole normale supérieure
adresse: 45 rue d'Ulm 75005 Paris
directrice_publication : Hélène Dessales
infographiste : Alban-Brice Pimpaud
auteur: Dessales H. et al.

locale: fr_FR
encoding: UTF-8


date: 2020
timezone: Europe/Paris
place : Paris

keep_files: ["potree/pointcloud"]

collections:
  contenus:
    output: true
    permalink: /:path